/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cg_lab1;

import java.awt.Color;
import javax.swing.JColorChooser;


public class Main extends javax.swing.JFrame {

    RGB rgb;
    CMYK cmyk;
    HSV hsv;
    LAB LAB;
    boolean blocked;

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        rgb = new RGB(mRGBSliderB,
                mRGBSliderG,
                mRGBSliderR,
                mRGBTextFieldB,
                mRGBTextFieldG,
                mRGBTextFieldR);

        cmyk = new CMYK(mCMYKSliderB,
                mCMYKSliderC,
                mCMYKSliderM,
                mCMYKSliderY,
                mCMYKTextFieldB,
                mCMYKTextFieldC,
                mCMYKTextFieldM,
                mCMYKTextFieldY,
                rgb);
        hsv = new HSV(mHSVSliderH,
                mHSVSliderS,
                mHSVSliderV,
                mHSVTextFieldH,
                mHSVTextFieldS,
                mHSVTextFieldV,
                rgb);

        LAB = new LAB(mLABSliderA,
                mLABSliderB,
                mLABTextFieldL,
                mLABTextFieldA,
                mLABTextFieldB,
                mLABSliderL,
                rgb);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
/*
        mRGBSliderR = new javax.swing.JSlider();
        mRGBSliderG = new javax.swing.JSlider();
        mRGBSliderB = new javax.swing.JSlider();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        mRGBTextFieldR = new javax.swing.JTextField();
        mRGBTextFieldG = new javax.swing.JTextField();
        mRGBTextFieldB = new javax.swing.JTextField();

 */
        mColorShow = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        mCMYKSliderC = new javax.swing.JSlider();
        mCMYKSliderM = new javax.swing.JSlider();
        mCMYKSliderY = new javax.swing.JSlider();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        mCMYKTextFieldC = new javax.swing.JTextField();
        mCMYKTextFieldM = new javax.swing.JTextField();
        mCMYKTextFieldY = new javax.swing.JTextField();
        mCMYKSliderB = new javax.swing.JSlider();
        jLabel9 = new javax.swing.JLabel();
        mCMYKTextFieldB = new javax.swing.JTextField();
        mHSVTextFieldV = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        mHSVSliderH = new javax.swing.JSlider();
        mHSVSliderS = new javax.swing.JSlider();
        mHSVSliderV = new javax.swing.JSlider();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        mHSVTextFieldH = new javax.swing.JTextField();
        mHSVTextFieldS = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        mLABTextFieldB = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        mLABSliderL = new javax.swing.JSlider();
        mLABSliderA = new javax.swing.JSlider();
        mLABSliderB = new javax.swing.JSlider();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        mLABTextFieldL = new javax.swing.JTextField();
        mLABTextFieldA = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);


        mColorShow.setBackground(new java.awt.Color(0, 0, 0));

        jButton1.setText("Choose Color");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout mColorShowLayout = new javax.swing.GroupLayout(mColorShow);
        mColorShow.setLayout(mColorShowLayout);
        mColorShowLayout.setHorizontalGroup(
            mColorShowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mColorShowLayout.createSequentialGroup()
                .addGap(334, 334, 334)
                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                .addGap(326, 326, 326))
        );
        mColorShowLayout.setVerticalGroup(
            mColorShowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mColorShowLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(40, 40, 40))
        );

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("RGB");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("CMYK");

        mCMYKSliderC.setMaximum(1000);
        mCMYKSliderC.setValue(0);
        mCMYKSliderC.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                mCMYKSliderCStateChanged(evt);
            }
        });

        mCMYKSliderM.setMaximum(1000);
        mCMYKSliderM.setValue(0);
        mCMYKSliderM.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                mCMYKSliderMStateChanged(evt);
            }
        });

        mCMYKSliderY.setMaximum(1000);
        mCMYKSliderY.setValue(0);
        mCMYKSliderY.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                mCMYKSliderYStateChanged(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 255, 255));
        jLabel6.setText("C");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 0, 255));
        jLabel7.setText("M");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 204, 0));
        jLabel8.setText("Y");

        mCMYKTextFieldC.setText("0");
        mCMYKTextFieldC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mCMYKTextFieldCActionPerformed(evt);
            }
        });

        mCMYKTextFieldM.setText("0");
        mCMYKTextFieldM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mCMYKTextFieldMActionPerformed(evt);
            }
        });

        mCMYKTextFieldY.setText("0");
        mCMYKTextFieldY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mCMYKTextFieldYActionPerformed(evt);
            }
        });

        mCMYKSliderB.setMaximum(1000);
        mCMYKSliderB.setValue(1000);
        mCMYKSliderB.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                mCMYKSliderBStateChanged(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("B");

        mCMYKTextFieldB.setText("0");
        mCMYKTextFieldB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mCMYKTextFieldBActionPerformed(evt);
            }
        });

        mHSVTextFieldV.setText("0");
        mHSVTextFieldV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mHSVTextFieldVActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setText("HSV");

        mHSVSliderH.setMaximum(359);
        mHSVSliderH.setValue(0);
        mHSVSliderH.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                mHSVSliderHStateChanged(evt);
            }
        });

        mHSVSliderS.setValue(0);
        mHSVSliderS.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                mHSVSliderSStateChanged(evt);
            }
        });

        mHSVSliderV.setValue(0);
        mHSVSliderV.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                mHSVSliderVStateChanged(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("H");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("S");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setText("V");

        mHSVTextFieldH.setText("0");
        mHSVTextFieldH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mHSVTextFieldHActionPerformed(evt);
            }
        });

        mHSVTextFieldS.setText("0");
        mHSVTextFieldS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mHSVTextFieldSActionPerformed(evt);
            }
        });

        jLabel14.setText("°");

        jLabel15.setText("%");

        jLabel16.setText("%");

        mLABTextFieldB.setText("0");
        mLABTextFieldB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mLUVTextFieldVActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel17.setText("Lab");

        mLABSliderL.setValue(0);
        mLABSliderL.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                mLUVSliderLStateChanged(evt);
            }
        });

        mLABSliderA.setMaximum(220);
        mLABSliderA.setMinimum(-134);
        mLABSliderA.setToolTipText("");
        mLABSliderA.setValue(0);
        mLABSliderA.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                mLUVSliderUStateChanged(evt);
            }
        });

        mLABSliderB.setMaximum(122);
        mLABSliderB.setMinimum(-140);
        mLABSliderB.setValue(0);
        mLABSliderB.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                mLUVSliderVStateChanged(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel18.setText("L");

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel19.setText("A");

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel20.setText("B");

        mLABTextFieldL.setText("0");
        mLABTextFieldL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mLUVTextFieldLActionPerformed(evt);
            }
        });

        mLABTextFieldA.setText("0");
        mLABTextFieldA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mLUVTextFieldUActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mColorShow, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(mCMYKSliderB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(mCMYKTextFieldB, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel5)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(mCMYKSliderY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(mCMYKTextFieldY))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(mCMYKSliderM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(mCMYKTextFieldM))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(mCMYKSliderC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(mCMYKTextFieldC, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(mHSVSliderV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(mHSVTextFieldV))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(mHSVSliderS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(mHSVTextFieldS))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(mHSVSliderH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(mHSVTextFieldH, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel16))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel18)
                            .addComponent(jLabel19)
                            .addComponent(jLabel20))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(mLABSliderB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(mLABTextFieldB))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(mLABSliderA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(mLABTextFieldA))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(mLABSliderL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(mLABTextFieldL, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(15, 15, 15))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(mCMYKSliderC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(mCMYKTextFieldC, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(mCMYKSliderM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(mCMYKTextFieldM, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(6, 6, 6))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(mCMYKSliderY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(mCMYKTextFieldY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(mCMYKSliderB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mCMYKTextFieldB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mColorShow, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(mHSVSliderH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(mHSVTextFieldH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel14)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(mHSVSliderS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(mHSVTextFieldS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel15)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(mHSVTextFieldV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel16))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel13)
                                .addComponent(mHSVSliderV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(mLABSliderL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18)
                            .addComponent(mLABTextFieldL, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(mLABSliderA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19)
                            .addComponent(mLABTextFieldA, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(mLABTextFieldB, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel20)
                                .addComponent(mLABSliderB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mRGBTextFieldRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mRGBTextFieldRActionPerformed
        mRGBTextChanged();
    }//GEN-LAST:event_mRGBTextFieldRActionPerformed

    private void mRGBTextFieldBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mRGBTextFieldBActionPerformed
        mRGBTextChanged();
    }//GEN-LAST:event_mRGBTextFieldBActionPerformed

    private void mRGBSliderRStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_mRGBSliderRStateChanged
        mRGBSliderChanged();
    }//GEN-LAST:event_mRGBSliderRStateChanged

    private void mRGBSliderGStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_mRGBSliderGStateChanged
        mRGBSliderChanged();
    }//GEN-LAST:event_mRGBSliderGStateChanged

    private void mRGBSliderBStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_mRGBSliderBStateChanged
        mRGBSliderChanged();
    }//GEN-LAST:event_mRGBSliderBStateChanged

    private void mRGBTextFieldGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mRGBTextFieldGActionPerformed
        mRGBTextChanged();
    }//GEN-LAST:event_mRGBTextFieldGActionPerformed

    private void mCMYKSliderCStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_mCMYKSliderCStateChanged
        mCMYKSliderChanged();
    }//GEN-LAST:event_mCMYKSliderCStateChanged

    private void mCMYKSliderMStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_mCMYKSliderMStateChanged
        mCMYKSliderChanged();
    }//GEN-LAST:event_mCMYKSliderMStateChanged

    private void mCMYKSliderYStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_mCMYKSliderYStateChanged
        mCMYKSliderChanged();
    }//GEN-LAST:event_mCMYKSliderYStateChanged

    private void mCMYKTextFieldCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mCMYKTextFieldCActionPerformed
        mCMYKTextChanged();
    }//GEN-LAST:event_mCMYKTextFieldCActionPerformed

    private void mCMYKTextFieldMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mCMYKTextFieldMActionPerformed
        mCMYKTextChanged();
    }//GEN-LAST:event_mCMYKTextFieldMActionPerformed

    private void mCMYKTextFieldYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mCMYKTextFieldYActionPerformed
        mCMYKTextChanged();
    }//GEN-LAST:event_mCMYKTextFieldYActionPerformed

    private void mCMYKSliderBStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_mCMYKSliderBStateChanged
        mCMYKSliderChanged();
    }//GEN-LAST:event_mCMYKSliderBStateChanged

    private void mCMYKTextFieldBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mCMYKTextFieldBActionPerformed
        mCMYKTextChanged();
    }//GEN-LAST:event_mCMYKTextFieldBActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Color c = JColorChooser.showDialog(null, "Choose a color", rgb.getColor());
        if (c == null) {
            return;
        }
        rgb.setR((float) c.getRed() / 255);
        rgb.setG((float) c.getGreen() / 255);
        rgb.setB((float) c.getBlue() / 255);
        blocked = true;
        //rgb.updateAll();
        cmyk.updateAll();
        hsv.updateAll();
        LAB.updateAll();
        updateColor();
        blocked = false;
    }//GEN-LAST:event_jButton1ActionPerformed

    private void mHSVTextFieldVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mHSVTextFieldVActionPerformed
        mHSVSTextChanged();
    }//GEN-LAST:event_mHSVTextFieldVActionPerformed

    private void mHSVSliderHStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_mHSVSliderHStateChanged
        mHSVSliderChanged();
    }//GEN-LAST:event_mHSVSliderHStateChanged

    private void mHSVSliderSStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_mHSVSliderSStateChanged
        mHSVSliderChanged();
    }//GEN-LAST:event_mHSVSliderSStateChanged

    private void mHSVSliderVStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_mHSVSliderVStateChanged
        mHSVSliderChanged();
    }//GEN-LAST:event_mHSVSliderVStateChanged

    private void mHSVTextFieldHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mHSVTextFieldHActionPerformed
        mHSVSTextChanged();
    }//GEN-LAST:event_mHSVTextFieldHActionPerformed

    private void mHSVTextFieldSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mHSVTextFieldSActionPerformed
        mHSVSTextChanged();
    }//GEN-LAST:event_mHSVTextFieldSActionPerformed

    private void mLUVTextFieldVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mLUVTextFieldVActionPerformed
        mLUVTextChanged();
    }//GEN-LAST:event_mLUVTextFieldVActionPerformed

    private void mLUVSliderLStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_mLUVSliderLStateChanged
        mLUVSliderChanged();
    }//GEN-LAST:event_mLUVSliderLStateChanged

    private void mLUVSliderUStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_mLUVSliderUStateChanged
        mLUVSliderChanged();
    }//GEN-LAST:event_mLUVSliderUStateChanged

    private void mLUVSliderVStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_mLUVSliderVStateChanged
        mLUVSliderChanged();
    }//GEN-LAST:event_mLUVSliderVStateChanged

    private void mLUVTextFieldLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mLUVTextFieldLActionPerformed
        mLUVTextChanged();
    }//GEN-LAST:event_mLUVTextFieldLActionPerformed

    private void mLUVTextFieldUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mLUVTextFieldUActionPerformed
        mLUVTextChanged();
    }//GEN-LAST:event_mLUVTextFieldUActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    private void updateColor() {
        mColorShow.setBackground(rgb.getColor());
    }

    private void mCMYKSliderChanged() {
        if (blocked) {
            return;
        }
        blocked = true;
        cmyk.sliderChanged();
        //rgb.updateAll();
        hsv.updateAll();
        LAB.updateAll();
        updateColor();
        blocked = false;
    }

    private void mCMYKTextChanged() {
        if (blocked) {
            return;
        }
        blocked = true;
        cmyk.textChanged();
        //rgb.updateAll();
        hsv.updateAll();
        LAB.updateAll();
        updateColor();
        blocked = false;
    }

    private void mRGBTextChanged() {
        if (blocked) {
            return;
        }
        blocked = true;
        //rgb.textChanged();
        cmyk.updateAll();
        hsv.updateAll();
        LAB.updateAll();
        updateColor();
        blocked = false;
    }

    private void mRGBSliderChanged() {
        if (blocked) {
            return;
        }
        blocked = true;
        //rgb.sliderChanged();
        cmyk.updateAll();
        hsv.updateAll();
        LAB.updateAll();
        updateColor();
        blocked = false;
    }

    private void mHSVSliderChanged() {
        if (blocked) {
            return;
        }
        blocked = true;
        hsv.sliderChanged();
        //rgb.updateAll();
        cmyk.updateAll();
        LAB.updateAll();
        updateColor();
        blocked = false;
    }

    private void mHSVSTextChanged() {
        if (blocked) {
            return;
        }
        blocked = true;
        hsv.textChanged();
        //rgb.updateAll();
        cmyk.updateAll();
        LAB.updateAll();
        updateColor();
        blocked = false;
    }

    private void mLUVTextChanged() {
        if (blocked) {
            return;
        }
        blocked = true;
        LAB.textChanged();
        //rgb.updateAll();
        cmyk.updateAll();
        hsv.updateAll();
        updateColor();
        blocked = false;
    }

    private void mLUVSliderChanged() {
        if (blocked) {
            return;
        }
        blocked = true;
        LAB.sliderChanged();
        //rgb.updateAll();
        cmyk.updateAll();
        hsv.updateAll();
        updateColor();
        blocked = false;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSlider mCMYKSliderB;
    private javax.swing.JSlider mCMYKSliderC;
    private javax.swing.JSlider mCMYKSliderM;
    private javax.swing.JSlider mCMYKSliderY;
    private javax.swing.JTextField mCMYKTextFieldB;
    private javax.swing.JTextField mCMYKTextFieldC;
    private javax.swing.JTextField mCMYKTextFieldM;
    private javax.swing.JTextField mCMYKTextFieldY;
    private javax.swing.JPanel mColorShow;
    private javax.swing.JSlider mHSVSliderH;
    private javax.swing.JSlider mHSVSliderS;
    private javax.swing.JSlider mHSVSliderV;
    private javax.swing.JTextField mHSVTextFieldH;
    private javax.swing.JTextField mHSVTextFieldS;
    private javax.swing.JTextField mHSVTextFieldV;
    private javax.swing.JSlider mLABSliderL;
    private javax.swing.JSlider mLABSliderA;
    private javax.swing.JSlider mLABSliderB;
    private javax.swing.JTextField mLABTextFieldL;
    private javax.swing.JTextField mLABTextFieldA;
    private javax.swing.JTextField mLABTextFieldB;
   private javax.swing.JSlider mRGBSliderB;
    private javax.swing.JSlider mRGBSliderG;
    private javax.swing.JSlider mRGBSliderR;
    private javax.swing.JTextField mRGBTextFieldB;
    private javax.swing.JTextField mRGBTextFieldG;
    private javax.swing.JTextField mRGBTextFieldR;


    // End of variables declaration//GEN-END:variables
}
